###########################################################################
#     Pieces - Andrew Belle
#   Written by Chutipon (Potter) Chutipanich 
#           2025-12-06
###########################################################################

###########################################################################
#
#   region Imports
#
###########################################################################

from sqlalchemy.orm import Session
from sqlalchemy import func

from . import models, schemas

###########################################################################
#
#   region Helpers
#
###########################################################################

###########################################################################
#
#   region Program Specific Globals
#
###########################################################################

###########################################################################
#
#   region Class Definitions
#
###########################################################################

class CategoryCRUD:
    ''' Category CRUD operations '''

    @staticmethod
    def getCategoryByID( db: Session, category_id: int ):
        return db.query( models.Category ).filter( models.Category.id == category_id ).first()

    @staticmethod
    def getCategoryByName( db: Session, name: str ):
        return db.query( models.Category ).filter( models.Category.name == name ).first()
    
    @staticmethod
    def getCategories( db: Session, skip: int = 0, limit: int = 100 ):
        return db.query( models.Category ).offset( skip ).limit( limit ).all()

    @staticmethod
    def createCategory( db: Session, category: schemas.CategoryCreate ):
        # Create the SQLAlchemy model instance
        db_category = models.Category( name=category.name )

        db.add( db_category ) # add to session
        db.commit() # commit to db

        db.refresh( db_category )  # Refresh to get the ID generated by the DB

        return db_category
    
    @staticmethod
    def deleteCategory( db: Session, category_id: int ):
        db_category = db.query( models.Category ).filter( models.Category.id == category_id ).first()
        if db_category:
            db.delete( db_category )
            db.commit()
            return True
        return False
    
class TransactionCRUD:
    ''' Transaction CRUD operations '''
    
    def getTransactions( db: Session, skip: int = 0, limit: int = 100 ):
        return db.query( models.Transaction ).offset( skip ).limit( limit ).all()

    def createTransaction( db: Session, transaction: schemas.TransactionCreate ):
        # Convert Pydantic model to dictionary and unpack it
        db_transaction = models.Transaction( **transaction.model_dump() )
        db.add( db_transaction ) # add to session
        db.commit() # commit to db
        db.refresh( db_transaction )  # Refresh to get the ID generated by the DB
        return db_transaction

    def deleteTransaction( db: Session, transaction_id: int ):
        # find transaction by id
        db_transaction = db.query( models.Transaction ).filter( models.Transaction.id == transaction_id ).first()
        # delete if exists
        if db_transaction:
            db.delete( db_transaction )
            db.commit()
            return True
        return False
    
def getExpensesByCategory( db: Session ):
    ''' Returns total expenses per category '''
    return db.query(
        models.Category.name.label( "category" ),
            func.sum( models.Transaction.amount ).label( "total" )
        ).join( models.Transaction ) \
            .filter( models.Transaction.type == "expense" ) \
            .group_by( models.Category.name ).all()

def getMonthlySummary(db: Session):
    ''' Returns total income and expenses grouped by month '''
    return db.query(
            # Extract YYYY-MM from the date column
            func.strftime("%Y-%m", models.Transaction.date).label("month"),
            models.Transaction.type,
            func.sum(models.Transaction.amount).label("total")
        ).group_by("month", models.Transaction.type).all()